massage_200 = 'Student registration successful'
massage_201 = 'Student Find successful'
massage_202 = 'Student password changed successfully'
massage_400 = 'Missing key information'
massage_401 = 'Student information duplicate'
massage_402 = 'For querying to this Student'
massage_403 = 'The Student and password do not match'
massage_500 = 'Missing information'

massage_203 = 'Book registration successful'
massage_204 = 'Book changed successfully'
massage_205 = 'Book Find successfully'
massage_405 = 'Book id duplication'
massage_406 = 'For querying to this Book is null'

massage_206 = 'Borrow registration successful'
massage_207 = 'Borrow Find successfully'
massage_208 = 'Borrow delete'
massage_407 = 'Borrow id duplication'
massage_409 = 'For querying to Borrow is null'

massage_209 = 'Manager registration successful'
massage_210 = 'Manager password changed successfully'
massage_211 = 'Manager Find successful'

massage_212 = 'return registration successful'
